-- Insert accessory products (covers and screen protectors)
-- Products include: Protection, Protection, and Protection

BEGIN;

INSERT INTO public.products (
  name,
  type,
  category,
  model,
  available_colors,
  available_storage,
  base_price,
  description,
  specifications,
  status,
  created_by,
  updated_by
) VALUES
  -- FUNDAS SILICONA
  ('Funda Silicona iPhone 11', 'accessory', 'protection', 'Funda Silicona iPhone 11',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 11',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 12/12 PRO', 'accessory', 'protection', 'Funda Silicona iPhone 12/12 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 12 y iPhone 12 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 13', 'accessory', 'protection', 'Funda Silicona iPhone 13',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 13',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 13 PRO', 'accessory', 'protection', 'Funda Silicona iPhone 13 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 13 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 13 PRO MAX', 'accessory', 'protection', 'Funda Silicona iPhone 13 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 13 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 14 PRO', 'accessory', 'protection', 'Funda Silicona iPhone 14 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 14 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 14 PRO MAX', 'accessory', 'protection', 'Funda Silicona iPhone 14 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 14 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 15', 'accessory', 'protection', 'Funda Silicona iPhone 15',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 15',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 16', 'accessory', 'protection', 'Funda Silicona iPhone 16',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 16',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 16 PRO', 'accessory', 'protection', 'Funda Silicona iPhone 16 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 16 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Silicona iPhone 16 PRO MAX', 'accessory', 'protection', 'Funda Silicona iPhone 16 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda de silicona para iPhone 16 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),

  -- FUNDAS ANTISHOCK
  ('Funda Antishock iPhone X/XS', 'accessory', 'protection', 'Funda Antishock iPhone X/XS',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone X y iPhone XS',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone XS MAX', 'accessory', 'protection', 'Funda Antishock iPhone XS MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone XS MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone XR', 'accessory', 'protection', 'Funda Antishock iPhone XR',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone XR',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 11', 'accessory', 'protection', 'Funda Antishock iPhone 11',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 11',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 11 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 11 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 11 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 11 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 11 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 11 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 12/12 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 12/12 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 12 y iPhone 12 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 12 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 12 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 12 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 13', 'accessory', 'protection', 'Funda Antishock iPhone 13',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 13',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 13 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 13 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 13 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 13 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 13 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 13 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 14', 'accessory', 'protection', 'Funda Antishock iPhone 14',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 14',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 14 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 14 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 14 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 14 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 14 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 14 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 15', 'accessory', 'protection', 'Funda Antishock iPhone 15',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 15',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 15 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 15 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 15 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 15 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 15 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 15 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 15 PLUS', 'accessory', 'protection', 'Funda Antishock iPhone 15 PLUS',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 15 PLUS',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 16', 'accessory', 'protection', 'Funda Antishock iPhone 16',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 16',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 16 E', 'accessory', 'protection', 'Funda Antishock iPhone 16 E',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 16 E',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 16 PLUS', 'accessory', 'protection', 'Funda Antishock iPhone 16 PLUS',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 16 PLUS',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 16 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 16 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 16 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 16 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 16 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 16 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 17', 'accessory', 'protection', 'Funda Antishock iPhone 17',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 17',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 17 AIR', 'accessory', 'protection', 'Funda Antishock iPhone 17 AIR',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 17 AIR',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 17 PRO', 'accessory', 'protection', 'Funda Antishock iPhone 17 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 17 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Funda Antishock iPhone 17 PRO MAX', 'accessory', 'protection', 'Funda Antishock iPhone 17 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Funda antishock para iPhone 17 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),

  -- VIDRIOS TEMPLADOS
  ('Vidrio Templado X / XS / 11PRO', 'accessory', 'protection', 'Vidrio Templado X / XS / 11PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone X, iPhone XS e iPhone 11 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 11 / XR', 'accessory', 'protection', 'Vidrio Templado 11 / XR',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 11 e iPhone XR',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 11 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 11 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 11 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 12 / 12 PRO', 'accessory', 'protection', 'Vidrio Templado 12 / 12 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 12 e iPhone 12 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 12 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 12 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 12 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 13 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 13 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 13 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 14 / 14 PRO', 'accessory', 'protection', 'Vidrio Templado 14 / 14 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 14 e iPhone 14 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 14 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 14 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 14 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 15 / 15 PRO', 'accessory', 'protection', 'Vidrio Templado 15 / 15 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 15 e iPhone 15 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 15 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 15 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 15 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 16', 'accessory', 'protection', 'Vidrio Templado 16',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 16',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 16E', 'accessory', 'protection', 'Vidrio Templado 16E',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 16E',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 16 PRO', 'accessory', 'protection', 'Vidrio Templado 16 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 16 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 16 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 16 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 16 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 17', 'accessory', 'protection', 'Vidrio Templado 17',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 17',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 17 AIR', 'accessory', 'protection', 'Vidrio Templado 17 AIR',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 17 AIR',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 17 PRO', 'accessory', 'protection', 'Vidrio Templado 17 PRO',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 17 PRO',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  ),
  ('Vidrio Templado 17 PRO MAX', 'accessory', 'protection', 'Vidrio Templado 17 PRO MAX',
   ARRAY[]::TEXT[],
   NULL,
   0.00,
   'Vidrio templado para iPhone 17 PRO MAX',
   '{}'::JSONB,
   'active',
   ''::UUID,
   ''::UUID
  );

COMMIT;

